const fs = require('fs');
const path = require('path');
const entry = fs.readFileSync(path.join(__dirname, 'main-source.js'), 'utf8');
let bundled = entry;
for (const [variable, file] of [['ops', 'vault-ops'], ['i18n', 'i18n']]) {
  const source = fs.readFileSync(path.join(__dirname, file + '.js'), 'utf8');
  bundled = bundled.replace(`const ${variable} = require('./${file}');`, () => `const ${variable} = (() => {\nconst module = { exports: {} };\n${source}\nreturn module.exports;\n})();`);
}
fs.writeFileSync(path.join(__dirname, 'main.js'), '// Generated by build.js. Edit main-source.js, vault-ops.js, and i18n.js.\n' + bundled);
console.log('Built main.js');
