const fs = require('fs');
const path = require('path');
const core = fs.readFileSync(path.join(__dirname, 'vault-ops.js'), 'utf8');
const entry = fs.readFileSync(path.join(__dirname, 'main-source.js'), 'utf8');
const bundled = entry.replace("const ops = require('./vault-ops');", () => 'const ops = (() => {\nconst module = { exports: {} };\n' + core + '\nreturn module.exports;\n})();');
fs.writeFileSync(path.join(__dirname, 'main.js'), '// Generated by build.js. Edit main-source.js and vault-ops.js.\n' + bundled);
console.log('Built main.js');
