// Generated by build.js. Edit main-source.js and vault-ops.js.
const { Plugin, PluginSettingTab, Modal, Setting, Notice, FileSystemAdapter } = require('obsidian');
const path = require('path');
const ops = (() => {
const module = { exports: {} };
const fs = require('fs/promises');
const path = require('path');
const crypto = require('crypto');

const ID = 'local-vault-template';
const CONFIGS = new Set(['templates.json', 'core-plugins.json', 'app.json', 'appearance.json']);
const BLOCKED = new Set(['.git', '.trash', 'node_modules', '.DS_Store']);
const hash = data => crypto.createHash('sha256').update(data).digest('hex');

function inside(root, target) {
  const rel = path.relative(root, target);
  return rel === '' || (!rel.startsWith('..' + path.sep) && rel !== '..' && !path.isAbsolute(rel));
}
function nameCheck(name) {
  if (!name || name.trim() !== name || /[<>:"/\\|?*\x00-\x1f]/.test(name) || /[. ]$/.test(name) || /^\.{1,2}$/.test(name) || /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name)) {
    throw new Error('请填写有效的文件夹名称，不要包含斜杠、冒号或末尾空格。');
  }
  if (name.length > 100) throw new Error('名称过长，请使用 100 个字符以内的名称。');
  return name;
}
async function folder(value) {
  if (!path.isAbsolute(value)) throw new Error('请填写文件夹的完整路径，例如 D:\\Obsidianhub。');
  const real = await fs.realpath(value);
  if (!(await fs.stat(real)).isDirectory()) throw new Error('路径不是文件夹：' + value);
  return real;
}
async function fileInside(root, relative) {
  if (path.isAbsolute(relative)) throw new Error('文件必须使用仓库内的相对路径。');
  const target = path.resolve(root, relative);
  if (!inside(root, target)) throw new Error('文件路径超出仓库：' + relative);
  let walk = root;
  for (const part of path.relative(root, target).split(path.sep)) {
    walk = path.join(walk, part);
    if ((await fs.lstat(walk)).isSymbolicLink()) throw new Error('模板不包含快捷链接或目录联接：' + relative);
  }
  if (!(await fs.stat(target)).isFile()) throw new Error('不是普通文件：' + relative);
  return target;
}
async function listTemplate(source) {
  const root = await folder(source);
  const files = [];
  async function walk(dir, prefix = '') {
    for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
      if (BLOCKED.has(entry.name)) continue;
      const relative = prefix ? prefix + '/' + entry.name : entry.name;
      if (relative.startsWith('.obsidian/') && !CONFIGS.has(relative.slice(10))) continue;
      if (entry.isSymbolicLink()) throw new Error('模板中包含快捷链接或目录联接：' + relative);
      if (entry.isDirectory()) await walk(path.join(dir, entry.name), relative);
      else if (entry.isFile()) files.push(relative);
    }
  }
  await walk(root);
  if (!files.some(f => f.toLowerCase().endsWith('.md'))) throw new Error('模板文件夹中没有 Markdown 笔记。');
  return { root, files: files.sort() };
}
async function destination(parent, name, forbidden) {
  const root = await folder(parent);
  const target = path.join(root, nameCheck(name));
  for (const protectedRoot of forbidden) {
    const real = await folder(protectedRoot);
    if (inside(real, target) || inside(target, real)) throw new Error('请将新文件夹放在当前仓库和模板文件夹之外，避免仓库嵌套。');
  }
  try { await fs.lstat(target); throw new Error('目标文件夹已经存在，请换一个名称：' + target); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  return target;
}
async function collect(root, files) {
  const entries = [];
  for (const relative of [...new Set(files)].sort()) {
    const source = await fileInside(root, relative);
    const bytes = await fs.readFile(source);
    entries.push({ relative: relative.replace(/\\/g, '/'), bytes });
  }
  return entries;
}
function put(entries, relative, object) {
  const bytes = Buffer.from(JSON.stringify(object, null, 2) + '\n');
  const existing = entries.find(e => e.relative === relative);
  if (existing) existing.bytes = bytes;
  else entries.push({ relative, bytes });
}
function coreSettings(entries) {
  const entry = entries.find(e => e.relative === '.obsidian/core-plugins.json');
  const value = entry ? JSON.parse(entry.bytes.toString('utf8').replace(/^\uFEFF/, '')) : { 'file-explorer': true, 'global-search': true, 'switcher': true, 'backlink': true, 'outline': true, 'command-palette': true, 'file-recovery': true };
  if (Array.isArray(value)) { if (!value.includes('templates')) value.push('templates'); }
  else if (value && typeof value === 'object') value.templates = true;
  else throw new Error('模板中的核心插件配置不是有效的对象或数组。');
  put(entries, '.obsidian/core-plugins.json', value);
}
async function writeNew(target, entries) {
  // Exclusive directory creation and file writes: an existing vault is never overwritten.
  await fs.mkdir(target);
  try {
    for (const entry of entries) {
      const out = path.resolve(target, entry.relative);
      if (!inside(target, out)) throw new Error('不合法的目标路径。');
      await fs.mkdir(path.dirname(out), { recursive: true });
      await fs.writeFile(out, entry.bytes, { flag: 'wx' });
      if (hash(await fs.readFile(out)) !== hash(entry.bytes)) throw new Error('写入校验失败：' + entry.relative);
    }
  } catch (error) {
    throw new Error('创建未完成，已写入的文件保留在 ' + target + '。请检查后使用另一个名称重试。原因：' + error.message);
  }
  return { target, files: entries.length, hashes: entries.map(e => ({ path: e.relative, sha256: hash(e.bytes) })) };
}
async function snapshot({ vaultRoot, selected, attachments = [], parent, name, templatePath, templateFolder = '模板' }) {
  const source = await folder(vaultRoot);
  if (!selected.length) throw new Error('请至少选择一篇笔记。');
  const protectedRoots = [source];
  if (templatePath) protectedRoots.push(templatePath);
  const target = await destination(parent, name, protectedRoots);
  const entries = await collect(source, [...selected, ...attachments]);
  const templateInfo = path.join(source, '.obsidian/templates.json');
  try {
    const original = JSON.parse((await fs.readFile(templateInfo, 'utf8')).replace(/^\uFEFF/, ''));
    templateFolder = original.folder || templateFolder;
  } catch (error) { if (error.code !== 'ENOENT') throw error; }
  put(entries, '.obsidian/templates.json', { folder: templateFolder, dateFormat: 'YYYY-MM-DD', timeFormat: 'HH:mm' });
  coreSettings(entries);
  return writeNew(target, entries);
}
async function createVault({ templatePath, parent, name, vaultRoot, pluginDir, settings }) {
  const template = await listTemplate(templatePath);
  const target = await destination(parent, name, [template.root, vaultRoot]);
  const entries = await collect(template.root, template.files);
  coreSettings(entries);
  const pluginRoot = await folder(pluginDir);
  for (const file of ['manifest.json', 'main.js', 'vault-ops.js', 'styles.css']) {
    const source = await fileInside(pluginRoot, file);
    entries.push({ relative: '.obsidian/plugins/' + ID + '/' + file, bytes: await fs.readFile(source) });
  }
  put(entries, '.obsidian/plugins/' + ID + '/data.json', { ...settings, templatePath: template.root, parentPath: path.dirname(target) });
  put(entries, '.obsidian/community-plugins.json', [ID]);
  return writeNew(target, entries);
}
module.exports = { ID, inside, nameCheck, folder, listTemplate, snapshot, createVault };

return module.exports;
})();

const DEFAULTS = { templatePath: '', parentPath: '', selected: ['开始使用.md', '仓库模板插件使用说明.md', '模板/Markdown常用语法笔记.md', '模板/学习笔记模板.md'] };
function description(el, text) { el.createEl('p', { text, cls: 'vault-template-muted' }); }
async function action(button, run) {
  button.setDisabled(true);
  try { await run(); }
  catch (error) { new Notice(error.message || String(error), 10000); console.error('[仓库模板]', error); }
  finally { button.setDisabled(false); }
}

class VaultTemplatePlugin extends Plugin {
  async onload() {
    if (!(this.app.vault.adapter instanceof FileSystemAdapter)) return;
    this.settings = { ...DEFAULTS, ...(await this.loadData()) };
    this.root = this.app.vault.adapter.getBasePath();
    this.settings.parentPath ||= path.dirname(this.root);
    this.settings.templatePath ||= path.join(path.dirname(this.root), '_仓库模板');
    this.addRibbonIcon('folder-plus', '仓库模板：设置模板 / 新建仓库', () => this.openHome());
    this.addCommand({ id: 'open', name: '打开仓库模板', callback: () => this.openHome() });
    this.addCommand({ id: 'set-template', name: '设置仓库模板', callback: () => new SaveTemplateModal(this).open() });
    this.addCommand({ id: 'create-vault', name: '从模板新建仓库', callback: () => new CreateVaultModal(this).open() });
    this.addSettingTab(new TemplateSettingTab(this.app, this));
  }
  openHome() { new HomeModal(this).open(); }
  async save() { await this.saveData(this.settings); }
  getPluginDir() { return path.join(this.root, this.app.vault.configDir, 'plugins', this.manifest.id); }
}

class HomeModal extends Modal {
  constructor(plugin) { super(plugin.app); this.plugin = plugin; }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass('vault-template-modal');
    contentEl.createEl('h2', { text: '仓库模板' });
    description(contentEl, '把常用笔记准备一次，之后的新仓库直接带上。');
    const card = contentEl.createDiv({ cls: 'vault-template-card' });
    card.createEl('strong', { text: '当前使用的模板' });
    card.createEl('p', { text: this.plugin.settings.templatePath, cls: 'vault-template-path' });
    new Setting(contentEl).setName('从模板新建仓库').setDesc('输入名称与存放位置，自动复制模板和本插件。')
      .addButton(b => b.setButtonText('新建仓库').setCta().onClick(() => { this.close(); new CreateVaultModal(this.plugin).open(); }));
    new Setting(contentEl).setName('设置仓库模板').setDesc('选择当前仓库中的笔记，保存成可重复使用的模板。')
      .addButton(b => b.setButtonText('设置模板').onClick(() => { this.close(); new SaveTemplateModal(this.plugin).open(); }));
    new Setting(contentEl).setName('Markdown 语法速查').setDesc('查看标题、代码、图片、链接和表格的写法。')
      .addButton(b => b.setButtonText('打开笔记').onClick(() => action(b, async () => {
        const note = this.app.vault.getAbstractFileByPath('模板/Markdown常用语法笔记.md');
        if (!note) throw new Error('当前仓库尚未包含速查笔记，请从准备好的模板创建仓库。');
        await this.app.workspace.getLeaf(false).openFile(note); this.close();
      })));
    description(contentEl, '请使用这里的“新建仓库”。Obsidian 自带的“创建新仓库”不会自动套用本插件的模板。');
  }
  onClose() { this.contentEl.empty(); }
}

class CreateVaultModal extends Modal {
  constructor(plugin) { super(plugin.app); this.plugin = plugin; }
  onOpen() {
    const el = this.contentEl;
    el.addClass('vault-template-modal');
    el.createEl('h2', { text: '从模板新建仓库' });
    let name = '', parent = this.plugin.settings.parentPath;
    description(el, '新仓库会带上模板里的笔记、附件和“仓库模板”插件。');
    new Setting(el).setName('仓库名称').addText(t => t.setPlaceholder('例如：项目笔记').onChange(v => { name = v; }));
    new Setting(el).setName('存放位置').setDesc('现有的父文件夹，例如 D:\\Obsidianhub。')
      .addText(t => t.setValue(parent).onChange(v => { parent = v.trim(); }));
    const preview = el.createEl('p', { cls: 'vault-template-path', text: '模板：' + this.plugin.settings.templatePath });
    let valid = false;
    ops.listTemplate(this.plugin.settings.templatePath).then(result => {
      valid = true;
      preview.setText('模板包含 ' + result.files.filter(f => f.endsWith('.md')).length + ' 篇笔记；' + result.files.length + ' 个文件。');
    }).catch(error => preview.setText('模板不可用：' + error.message));
    new Setting(el).addButton(b => b.setButtonText('创建仓库').setCta().onClick(() => action(b, async () => {
      if (!valid) throw new Error('请先在“设置仓库模板”中指定可用的模板。');
      const result = await ops.createVault({ templatePath: this.plugin.settings.templatePath, parent, name: name.trim(), vaultRoot: this.plugin.root, pluginDir: this.plugin.getPluginDir(), settings: this.plugin.settings });
      this.plugin.settings.parentPath = parent;
      try { await this.plugin.save(); } catch (error) { new Notice('仓库已创建，但默认位置未能保存：' + error.message); }
      this.close(); new CreatedModal(this.plugin, result).open();
    }))).addButton(b => b.setButtonText('取消').onClick(() => this.close()));
  }
  onClose() { this.contentEl.empty(); }
}

class CreatedModal extends Modal {
  constructor(plugin, result) { super(plugin.app); this.result = result; }
  onOpen() {
    const el = this.contentEl;
    el.createEl('h2', { text: '仓库已创建' });
    el.createEl('p', { text: this.result.target, cls: 'vault-template-path' });
    description(el, '首次打开时，在仓库管理器中选择“打开文件夹为仓库”，然后选择上面的文件夹。');
    description(el, '新仓库已携带本插件。首次打开如处于受限模式，请在第三方插件设置中启用“仓库模板”。');
    new Setting(el).addButton(b => b.setButtonText('复制路径').onClick(() => action(b, async () => {
      await navigator.clipboard.writeText(this.result.target); new Notice('仓库路径已复制');
    }))).addButton(b => b.setButtonText('打开仓库管理器').setCta().onClick(() => {
      window.open('obsidian://choose-vault');
    }));
  }
  onClose() { this.contentEl.empty(); }
}

class SaveTemplateModal extends Modal {
  constructor(plugin) { super(plugin.app); this.plugin = plugin; }
  onOpen() {
    const el = this.contentEl;
    el.addClass('vault-template-modal');
    el.createEl('h2', { text: '设置仓库模板' });
    description(el, '勾选希望每个新仓库都具备的笔记。保存的是独立副本，后续修改原笔记不会自动改变已有模板。');
    let existing = this.plugin.settings.templatePath;
    new Setting(el).setName('使用已有模板文件夹').addText(t => t.setValue(existing).onChange(v => { existing = v.trim(); }))
      .addButton(b => b.setButtonText('设为当前模板').onClick(() => action(b, async () => {
        const result = await ops.listTemplate(existing);
        this.plugin.settings.templatePath = result.root;
        await this.plugin.save(); new Notice('已设置仓库模板'); this.close(); this.plugin.openHome();
      })));
    el.createEl('h3', { text: '从当前仓库保存新模板' });
    const files = this.app.vault.getMarkdownFiles().sort((a, b) => a.path.localeCompare(b.path));
    const selected = new Set(this.plugin.settings.selected.filter(p => files.some(f => f.path === p)));
    let query = '';
    const search = new Setting(el).setName('选择笔记');
    search.addText(t => t.setPlaceholder('输入文件名筛选').onChange(v => { query = v.toLowerCase(); render(); }));
    const count = el.createEl('p', { cls: 'vault-template-muted' });
    const list = el.createDiv({ cls: 'vault-template-list' });
    const render = () => {
      list.empty(); count.setText('已选择 ' + selected.size + ' 篇笔记');
      for (const file of files.filter(f => f.path.toLowerCase().includes(query))) {
        new Setting(list).setName(file.path).addToggle(t => t.setValue(selected.has(file.path)).onChange(on => {
          if (on) selected.add(file.path); else selected.delete(file.path);
          count.setText('已选择 ' + selected.size + ' 篇笔记');
        }));
      }
    };
    render();
    let parent = this.plugin.settings.parentPath;
    const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
    let name = '仓库模板-' + stamp;
    new Setting(el).setName('模板名称').addText(t => t.setValue(name).onChange(v => { name = v; }));
    new Setting(el).setName('模板存放位置').setDesc('模板应保存在当前仓库之外。')
      .addText(t => t.setValue(parent).onChange(v => { parent = v.trim(); }));
    description(el, '会一并复制 Obsidian 已识别的图片、PDF 等附件引用；关联笔记请自行勾选。');
    new Setting(el).addButton(b => b.setButtonText('保存并设为仓库模板').setCta().onClick(() => action(b, async () => {
      const attachments = new Set();
      for (const file of selected) {
        for (const linked of Object.keys(this.app.metadataCache.resolvedLinks[file] || {})) {
          const item = this.app.vault.getAbstractFileByPath(linked);
          if (item && item.extension && !['md', 'canvas', 'base'].includes(item.extension)) attachments.add(linked);
        }
      }
      const result = await ops.snapshot({ vaultRoot: this.plugin.root, selected: [...selected], attachments: [...attachments], parent, name: name.trim() });
      this.plugin.settings.templatePath = result.target;
      this.plugin.settings.selected = [...selected];
      await this.plugin.save(); new Notice('已保存模板，可用于创建新仓库'); this.close(); this.plugin.openHome();
    })));
  }
  onClose() { this.contentEl.empty(); }
}

class TemplateSettingTab extends PluginSettingTab {
  constructor(app, plugin) { super(app, plugin); this.plugin = plugin; }
  display() {
    this.containerEl.empty();
    this.containerEl.createEl('h2', { text: '仓库模板' });
    description(this.containerEl, '模板：' + this.plugin.settings.templatePath);
    new Setting(this.containerEl).setName('管理仓库模板').setDesc('选择模板内容，或从模板新建仓库。')
      .addButton(b => b.setButtonText('打开').setCta().onClick(() => this.plugin.openHome()));
    description(this.containerEl, '本插件仅在你点击保存或创建时写入文件。不会监控文件夹或自动修改其他已存在的仓库。');
  }
}

module.exports = VaultTemplatePlugin;
