// Generated by build.js. Edit main-source.js, vault-ops.js, and i18n.js.
const { Plugin, PluginSettingTab, Modal, Setting, Notice, FileSystemAdapter, getLanguage, setTooltip } = require('obsidian');
const path = require('path');
const ops = (() => {
const module = { exports: {} };
const fs = require('fs/promises');
const path = require('path');
const crypto = require('crypto');

const ID = 'local-vault-template';
const CONFIGS = new Set(['templates.json', 'core-plugins.json', 'app.json', 'appearance.json']);
const BLOCKED = new Set(['.git', '.trash', 'node_modules', '.DS_Store']);
const hash = data => crypto.createHash('sha256').update(data).digest('hex');
class TemplateError extends Error {
  constructor(code, values = {}, cause) {
    super(code);
    this.templateCode = code;
    this.values = values;
    this.cause = cause;
  }
}

function inside(root, target) {
  const rel = path.relative(root, target);
  return rel === '' || (!rel.startsWith('..' + path.sep) && rel !== '..' && !path.isAbsolute(rel));
}
function nameCheck(name) {
  if (!name || name.trim() !== name || /[<>:"/\\|?*\x00-\x1f]/.test(name) || /[. ]$/.test(name) || /^\.{1,2}$/.test(name) || /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name)) {
    throw new TemplateError('invalidName');
  }
  if (name.length > 100) throw new TemplateError('longName');
  return name;
}
async function folder(value) {
  if (!path.isAbsolute(value)) throw new TemplateError('absolutePath');
  const real = await fs.realpath(value);
  if (!(await fs.stat(real)).isDirectory()) throw new TemplateError('notFolder', { path: value });
  return real;
}
async function fileInside(root, relative) {
  if (path.isAbsolute(relative)) throw new TemplateError('relativePath');
  const target = path.resolve(root, relative);
  if (!inside(root, target)) throw new TemplateError('outsideVault', { path: relative });
  let walk = root;
  for (const part of path.relative(root, target).split(path.sep)) {
    walk = path.join(walk, part);
    if ((await fs.lstat(walk)).isSymbolicLink()) throw new TemplateError('symlink', { path: relative });
  }
  if (!(await fs.stat(target)).isFile()) throw new TemplateError('notFile', { path: relative });
  return target;
}
async function listTemplate(source) {
  const root = await folder(source);
  const files = [];
  async function walk(dir, prefix = '') {
    for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
      if (BLOCKED.has(entry.name)) continue;
      const relative = prefix ? prefix + '/' + entry.name : entry.name;
      if (relative.startsWith('.obsidian/') && !CONFIGS.has(relative.slice(10))) continue;
      if (entry.isSymbolicLink()) throw new TemplateError('symlink', { path: relative });
      if (entry.isDirectory()) await walk(path.join(dir, entry.name), relative);
      else if (entry.isFile()) files.push(relative);
    }
  }
  await walk(root);
  if (!files.some(f => f.toLowerCase().endsWith('.md'))) throw new TemplateError('emptyTemplate');
  return { root, files: files.sort() };
}
async function destination(parent, name, forbidden) {
  const root = await folder(parent);
  const target = path.join(root, nameCheck(name));
  for (const protectedRoot of forbidden) {
    const real = await folder(protectedRoot);
    if (inside(real, target) || inside(target, real)) throw new TemplateError('nested');
  }
  try { await fs.lstat(target); throw new TemplateError('exists', { path: target }); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  return target;
}
async function collect(root, files) {
  const entries = [];
  for (const relative of [...new Set(files)].sort()) {
    const source = await fileInside(root, relative);
    const bytes = await fs.readFile(source);
    entries.push({ relative: relative.replace(/\\/g, '/'), bytes });
  }
  return entries;
}
function put(entries, relative, object) {
  const bytes = Buffer.from(JSON.stringify(object, null, 2) + '\n');
  const existing = entries.find(e => e.relative === relative);
  if (existing) existing.bytes = bytes;
  else entries.push({ relative, bytes });
}
function coreSettings(entries) {
  const entry = entries.find(e => e.relative === '.obsidian/core-plugins.json');
  const value = entry ? JSON.parse(entry.bytes.toString('utf8').replace(/^\uFEFF/, '')) : { 'file-explorer': true, 'global-search': true, 'switcher': true, 'backlink': true, 'outline': true, 'command-palette': true, 'file-recovery': true };
  if (Array.isArray(value)) { if (!value.includes('templates')) value.push('templates'); }
  else if (value && typeof value === 'object') value.templates = true;
  else throw new TemplateError('invalidCore');
  put(entries, '.obsidian/core-plugins.json', value);
}
async function writeNew(target, entries) {
  // Exclusive directory creation and file writes: an existing vault is never overwritten.
  await fs.mkdir(target);
  try {
    for (const entry of entries) {
      const out = path.resolve(target, entry.relative);
      if (!inside(target, out)) throw new TemplateError('invalidTarget');
      await fs.mkdir(path.dirname(out), { recursive: true });
      await fs.writeFile(out, entry.bytes, { flag: 'wx' });
      if (hash(await fs.readFile(out)) !== hash(entry.bytes)) throw new TemplateError('verifyFailed', { path: entry.relative });
    }
  } catch (error) {
    throw new TemplateError('partial', { path: target }, error);
  }
  return { target, files: entries.length, hashes: entries.map(e => ({ path: e.relative, sha256: hash(e.bytes) })) };
}
async function snapshot({ vaultRoot, selected, attachments = [], parent, name, templatePath, templateFolder = '模板', configDir = '.obsidian' }) {
  const source = await folder(vaultRoot);
  if (!selected.length) throw new TemplateError('selectOne');
  const protectedRoots = [source];
  if (templatePath) protectedRoots.push(templatePath);
  const target = await destination(parent, name, protectedRoots);
  const entries = await collect(source, [...selected, ...attachments]);
  const templateInfo = path.join(source, configDir, 'templates.json');
  try {
    const original = JSON.parse((await fs.readFile(templateInfo, 'utf8')).replace(/^\uFEFF/, ''));
    templateFolder = original.folder || templateFolder;
  } catch (error) { if (error.code !== 'ENOENT') throw error; }
  put(entries, '.obsidian/templates.json', { folder: templateFolder, dateFormat: 'YYYY-MM-DD', timeFormat: 'HH:mm' });
  coreSettings(entries);
  return writeNew(target, entries);
}
async function createVault({ templatePath, parent, name, vaultRoot, pluginDir, settings }) {
  const template = await listTemplate(templatePath);
  const target = await destination(parent, name, [template.root, vaultRoot]);
  const entries = await collect(template.root, template.files);
  coreSettings(entries);
  const pluginRoot = await folder(pluginDir);
  for (const file of ['manifest.json', 'main.js', 'styles.css']) {
    const source = await fileInside(pluginRoot, file);
    entries.push({ relative: '.obsidian/plugins/' + ID + '/' + file, bytes: await fs.readFile(source) });
  }
  put(entries, '.obsidian/plugins/' + ID + '/data.json', { ...settings, templatePath: template.root, parentPath: path.dirname(target) });
  put(entries, '.obsidian/community-plugins.json', [ID]);
  return writeNew(target, entries);
}
module.exports = { ID, TemplateError, inside, nameCheck, folder, listTemplate, snapshot, createVault };

return module.exports;
})();
const i18n = (() => {
const module = { exports: {} };
const messages = {
  en: {
    title: 'Template vault', ribbon: 'Template vault: configure or create a vault',
    openCommand: 'Open template manager', setCommand: 'Set vault template', createCommand: 'Create vault from template',
    language: 'Language', languageHint: 'Auto uses Chinese for Chinese Obsidian clients, and English otherwise.', auto: 'Auto (follow Obsidian)',
    intro: 'Prepare your essential notes once, and include them in each new vault.', current: 'Current template',
    createTitle: 'Create vault from template', createHint: 'Choose a name and location to copy the template and this plugin.', create: 'New vault',
    setTitle: 'Set vault template', setHint: 'Save selected notes from this vault as a reusable template.', set: 'Set template',
    guide: 'Markdown reference', guideHint: 'Look up headings, code, images, links, and tables.', openNote: 'Open note',
    missingGuide: 'This vault has no bundled Markdown reference. Create a vault using the example template first.',
    nativeHint: 'Use New vault here. Obsidian’s built-in Create new vault does not apply this template.',
    createIntro: 'The new vault will include the template’s notes, attachments, and this plugin.',
    vaultName: 'Vault name', vaultExample: 'For example: Project notes', location: 'Parent folder', locationHint: 'An existing folder, for example D:\\Notes.',
    templatePath: 'Template: {path}', preview: '{notes} notes and {files} files in this template.', unavailable: 'Template unavailable: {reason}',
    createButton: 'Create vault', chooseFirst: 'Select an available template in Set vault template first.',
    locationNotSaved: 'The vault was created, but its default location could not be saved: {reason}', cancel: 'Cancel',
    created: 'Vault created', openInstructions: 'In the vault manager, select Open folder as vault and choose the folder above.',
    enableInstructions: 'This plugin is included. If the new vault opens in Restricted mode, enable Template Vault in Community plugins.',
    copyPath: 'Copy path', copied: 'Vault path copied', manager: 'Open vault manager',
    saveIntro: 'Select the notes each new vault should contain. A template is an independent snapshot, not a live copy.',
    existingFolder: 'Use an existing template folder', useTemplate: 'Use this template', templateSet: 'Vault template selected',
    saveHeading: 'Save a template from this vault', selectNotes: 'Select notes', search: 'Filter by file name', selected: '{count} notes selected',
    templateName: 'Template name', templatePrefix: 'Vault-template-', templateLocation: 'Template parent folder', outsideHint: 'Store the template outside this vault.',
    attachmentHint: 'Recognized images, PDFs, and other attachments are included. Select linked notes separately if you need them.',
    saveTemplate: 'Save and use template', saved: 'Template saved and ready for new vaults',
    manage: 'Manage vault templates', manageHint: 'Choose template content or create a new vault.', open: 'Open',
    localHint: 'Files are written only when you save or create. No background monitoring or changes to other existing vaults.',
    invalidName: 'Enter a valid folder name without slashes, colons, or trailing spaces.', longName: 'Use a name of 100 characters or fewer.',
    absolutePath: 'Enter a full folder path, for example D:\\Notes.', notFolder: 'Not a folder: {path}',
    relativePath: 'Files must use paths relative to the vault.', outsideVault: 'The file path is outside the vault: {path}',
    symlink: 'Templates cannot include symbolic links or directory junctions: {path}', notFile: 'Not a regular file: {path}',
    emptyTemplate: 'The template folder contains no Markdown notes.', nested: 'Choose a folder outside the current vault and template to avoid nested vaults.',
    exists: 'The target folder already exists. Choose another name: {path}', invalidCore: 'The core plugin configuration must be a JSON object or array.',
    invalidTarget: 'Invalid destination path.', verifyFailed: 'File verification failed: {path}',
    partial: 'Creation did not finish. Partial files remain at {path}. Check them and retry with another name. Reason: {reason}',
    selectOne: 'Select at least one note.', missingPath: 'File or folder not found: {path}', denied: 'Permission denied: {path}',
    badJson: 'A configuration file contains invalid JSON.', unknownError: 'Operation failed: {reason}',
  },
  zh: {
    title: '仓库模板', ribbon: '仓库模板：设置模板 / 新建仓库',
    openCommand: '打开仓库模板', setCommand: '设置仓库模板', createCommand: '从模板新建仓库',
    language: '界面语言', languageHint: '自动模式下，中文 Obsidian 客户端使用中文，其余使用英文。', auto: '自动（跟随 Obsidian）',
    intro: '把常用笔记准备一次，之后的新仓库直接带上。', current: '当前使用的模板',
    createTitle: '从模板新建仓库', createHint: '输入名称与存放位置，自动复制模板和本插件。', create: '新建仓库',
    setTitle: '设置仓库模板', setHint: '选择当前仓库中的笔记，保存成可重复使用的模板。', set: '设置模板',
    guide: 'Markdown 语法速查', guideHint: '查看标题、代码、图片、链接和表格的写法。', openNote: '打开笔记',
    missingGuide: '当前仓库尚未包含速查笔记，请从示例模板创建仓库。',
    nativeHint: '请使用这里的“新建仓库”。Obsidian 自带的“创建新仓库”不会自动套用此模板。',
    createIntro: '新仓库会带上模板里的笔记、附件和本插件。',
    vaultName: '仓库名称', vaultExample: '例如：项目笔记', location: '存放位置', locationHint: '现有的父文件夹，例如 D:\\Notes。',
    templatePath: '模板：{path}', preview: '模板包含 {notes} 篇笔记，共 {files} 个文件。', unavailable: '模板不可用：{reason}',
    createButton: '创建仓库', chooseFirst: '请先在“设置仓库模板”中指定可用的模板。',
    locationNotSaved: '仓库已创建，但默认位置未能保存：{reason}', cancel: '取消',
    created: '仓库已创建', openInstructions: '在仓库管理器中选择“打开文件夹为仓库”，然后选择上面的文件夹。',
    enableInstructions: '新仓库已携带本插件。若处于受限模式，请在第三方插件设置中启用 Template Vault（仓库模板）。',
    copyPath: '复制路径', copied: '仓库路径已复制', manager: '打开仓库管理器',
    saveIntro: '勾选希望每个新仓库都具备的笔记。保存的是独立副本，后续修改原笔记不会自动改变已有模板。',
    existingFolder: '使用已有模板文件夹', useTemplate: '设为当前模板', templateSet: '已设置仓库模板',
    saveHeading: '从当前仓库保存新模板', selectNotes: '选择笔记', search: '输入文件名筛选', selected: '已选择 {count} 篇笔记',
    templateName: '模板名称', templatePrefix: '仓库模板-', templateLocation: '模板存放位置', outsideHint: '模板应保存在当前仓库之外。',
    attachmentHint: '会一并复制已识别的图片、PDF 等附件引用；关联笔记请自行勾选。',
    saveTemplate: '保存并设为仓库模板', saved: '已保存模板，可用于创建新仓库',
    manage: '管理仓库模板', manageHint: '选择模板内容，或从模板新建仓库。', open: '打开',
    localHint: '仅在点击保存或创建时写入文件。不会后台监控或自动修改其他已有仓库。',
    invalidName: '请填写有效的文件夹名称，不要包含斜杠、冒号或末尾空格。', longName: '名称过长，请使用 100 个字符以内的名称。',
    absolutePath: '请填写文件夹的完整路径，例如 D:\\Notes。', notFolder: '路径不是文件夹：{path}',
    relativePath: '文件必须使用仓库内的相对路径。', outsideVault: '文件路径超出仓库：{path}',
    symlink: '模板不包含符号链接或目录联接：{path}', notFile: '不是普通文件：{path}',
    emptyTemplate: '模板文件夹中没有 Markdown 笔记。', nested: '请将新文件夹放在当前仓库和模板之外，避免仓库嵌套。',
    exists: '目标文件夹已经存在，请换一个名称：{path}', invalidCore: '核心插件配置必须是 JSON 对象或数组。',
    invalidTarget: '不合法的目标路径。', verifyFailed: '写入校验失败：{path}',
    partial: '创建未完成，部分文件保留在 {path}。请检查后使用另一个名称重试。原因：{reason}',
    selectOne: '请至少选择一篇笔记。', missingPath: '找不到文件或文件夹：{path}', denied: '没有访问权限：{path}',
    badJson: '配置文件中的 JSON 格式有误。', unknownError: '操作失败：{reason}',
  },
};
function resolveLanguage(preference, clientLanguage) {
  if (preference === 'en' || preference === 'zh') return preference;
  return typeof clientLanguage === 'string' && /^zh(?:[-_]|$)/i.test(clientLanguage.trim()) ? 'zh' : 'en';
}
function translate(language, key, values = {}) {
  const template = (messages[language] || messages.en)[key] ?? messages.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (match, name) => values[name] === undefined ? match : String(values[name]));
}
function formatError(error, language) {
  if (error?.templateCode) {
    const values = { ...error.values };
    if (error.cause) values.reason = formatError(error.cause, language);
    return translate(language, error.templateCode, values);
  }
  if (error?.code === 'ENOENT') return translate(language, 'missingPath', { path: error.path || '' });
  if (['EACCES', 'EPERM'].includes(error?.code)) return translate(language, 'denied', { path: error.path || '' });
  if (error instanceof SyntaxError) return translate(language, 'badJson');
  return translate(language, 'unknownError', { reason: error?.message || String(error) });
}
module.exports = { messages, resolveLanguage, translate, formatError };

return module.exports;
})();

const DEFAULTS = { language: 'auto', templatePath: '', parentPath: '', selected: ['开始使用.md', '仓库模板插件使用说明.md', '模板/Markdown常用语法笔记.md', '模板/学习笔记模板.md'] };
function description(el, text) { el.createEl('p', { text, cls: 'vault-template-muted' }); }
async function action(plugin, button, run) {
  button.setDisabled(true);
  try { await run(); }
  catch (error) { new Notice(plugin.error(error), 10000); console.error('[Template Vault]', error); }
  finally { button.setDisabled(false); }
}
function languageSetting(el, plugin) {
  new Setting(el).setName(plugin.t('language')).setDesc(plugin.t('languageHint')).addDropdown(dropdown => {
    dropdown.addOption('auto', plugin.t('auto')).addOption('en', 'English').addOption('zh', '中文')
      .setValue(plugin.settings.language).onChange(value => action(plugin, dropdown, () => plugin.setLanguage(value)));
  });
}

class VaultTemplatePlugin extends Plugin {
  async onload() {
    if (!(this.app.vault.adapter instanceof FileSystemAdapter)) return;
    this.settings = { ...DEFAULTS, ...(await this.loadData()) };
    if (!['auto', 'en', 'zh'].includes(this.settings.language)) this.settings.language = 'auto';
    if (!Array.isArray(this.settings.selected)) this.settings.selected = [...DEFAULTS.selected];
    this.modals = new Set();
    this.root = this.app.vault.adapter.getBasePath();
    this.settings.parentPath ||= path.dirname(this.root);
    this.settings.templatePath ||= path.join(path.dirname(this.root), '_仓库模板');
    this.ribbon = this.addRibbonIcon('folder-plus', this.t('ribbon'), () => this.openHome());
    this.commands = [
      { id: 'open', key: 'openCommand', callback: () => this.openHome() },
      { id: 'set-template', key: 'setCommand', callback: () => new SaveTemplateModal(this).open() },
      { id: 'create-vault', key: 'createCommand', callback: () => new CreateVaultModal(this).open() },
    ].map(({ id, key, callback }) => ({ key, command: this.addCommand({ id, name: this.t(key), callback }) }));
    this.settingTab = new TemplateSettingTab(this.app, this);
    this.addSettingTab(this.settingTab);
  }
  locale() {
    let client;
    try { client = getLanguage(); } catch { client = 'en'; }
    return i18n.resolveLanguage(this.settings.language, client);
  }
  t(key, values) { return i18n.translate(this.locale(), key, values); }
  error(error) { return i18n.formatError(error, this.locale()); }
  async setLanguage(value) {
    const previous = this.settings.language;
    this.settings.language = ['auto', 'en', 'zh'].includes(value) ? value : 'auto';
    try { await this.save(); } catch (error) { this.settings.language = previous; throw error; }
    setTooltip(this.ribbon, this.t('ribbon'));
    this.ribbon.setAttribute('aria-label', this.t('ribbon'));
    for (const { key, command } of this.commands) command.name = this.manifest.name + ': ' + this.t(key);
    for (const modal of this.modals) modal.render();
    this.settingTab.display();
  }
  openHome() { new HomeModal(this).open(); }
  async save() { await this.saveData(this.settings); }
  getPluginDir() { return path.join(this.root, this.app.vault.configDir, 'plugins', this.manifest.id); }
  onunload() { for (const modal of [...(this.modals || [])]) modal.close(); }
}

class TemplateModal extends Modal {
  constructor(plugin) { super(plugin.app); this.plugin = plugin; this.t = (key, values) => plugin.t(key, values); }
  onOpen() { this.plugin.modals.add(this); this.render(); }
  onClose() { this.plugin.modals.delete(this); this.contentEl.empty(); }
  begin(title) { this.contentEl.empty(); this.contentEl.addClass('vault-template-modal'); this.setTitle(this.t(title)); return this.contentEl; }
  run(button, callback) { return action(this.plugin, button, callback); }
}

class HomeModal extends TemplateModal {
  render() {
    const el = this.begin('title');
    languageSetting(el, this.plugin);
    description(el, this.t('intro'));
    const card = el.createDiv({ cls: 'vault-template-card' });
    card.createEl('strong', { text: this.t('current') });
    card.createEl('p', { text: this.plugin.settings.templatePath, cls: 'vault-template-path' });
    new Setting(el).setName(this.t('createTitle')).setDesc(this.t('createHint'))
      .addButton(b => b.setButtonText(this.t('create')).setCta().onClick(() => { this.close(); new CreateVaultModal(this.plugin).open(); }));
    new Setting(el).setName(this.t('setTitle')).setDesc(this.t('setHint'))
      .addButton(b => b.setButtonText(this.t('set')).onClick(() => { this.close(); new SaveTemplateModal(this.plugin).open(); }));
    new Setting(el).setName(this.t('guide')).setDesc(this.t('guideHint'))
      .addButton(b => b.setButtonText(this.t('openNote')).onClick(() => this.run(b, async () => {
        const note = this.app.vault.getAbstractFileByPath('模板/Markdown常用语法笔记.md');
        if (!note) throw new ops.TemplateError('missingGuide');
        await this.app.workspace.getLeaf(false).openFile(note); this.close();
      })));
    description(el, this.t('nativeHint'));
  }
}

class CreateVaultModal extends TemplateModal {
  constructor(plugin) { super(plugin); this.name = ''; this.parent = plugin.settings.parentPath; }
  render() {
    const el = this.begin('createTitle');
    description(el, this.t('createIntro'));
    new Setting(el).setName(this.t('vaultName')).addText(t => t.setValue(this.name).setPlaceholder(this.t('vaultExample')).onChange(v => { this.name = v; }));
    new Setting(el).setName(this.t('location')).setDesc(this.t('locationHint'))
      .addText(t => t.setValue(this.parent).onChange(v => { this.parent = v.trim(); }));
    const preview = el.createEl('p', { cls: 'vault-template-path', text: this.t('templatePath', { path: this.plugin.settings.templatePath }) });
    ops.listTemplate(this.plugin.settings.templatePath).then(result => {
      preview.setText(this.t('preview', { notes: result.files.filter(f => f.toLowerCase().endsWith('.md')).length, files: result.files.length }));
    }).catch(error => preview.setText(this.t('unavailable', { reason: this.plugin.error(error) })));
    new Setting(el).addButton(b => b.setButtonText(this.t('createButton')).setCta().onClick(() => this.run(b, async () => {
      const result = await ops.createVault({ templatePath: this.plugin.settings.templatePath, parent: this.parent, name: this.name.trim(), vaultRoot: this.plugin.root, pluginDir: this.plugin.getPluginDir(), settings: this.plugin.settings });
      this.plugin.settings.parentPath = this.parent;
      try { await this.plugin.save(); } catch (error) { new Notice(this.t('locationNotSaved', { reason: this.plugin.error(error) })); }
      this.close(); new CreatedModal(this.plugin, result).open();
    }))).addButton(b => b.setButtonText(this.t('cancel')).onClick(() => this.close()));
  }
}

class CreatedModal extends TemplateModal {
  constructor(plugin, result) { super(plugin); this.result = result; }
  render() {
    const el = this.begin('created');
    el.createEl('p', { text: this.result.target, cls: 'vault-template-path' });
    description(el, this.t('openInstructions'));
    description(el, this.t('enableInstructions'));
    new Setting(el).addButton(b => b.setButtonText(this.t('copyPath')).onClick(() => this.run(b, async () => {
      await navigator.clipboard.writeText(this.result.target); new Notice(this.t('copied'));
    }))).addButton(b => b.setButtonText(this.t('manager')).setCta().onClick(() => { window.open('obsidian://choose-vault'); }));
  }
}

class SaveTemplateModal extends TemplateModal {
  constructor(plugin) {
    super(plugin);
    this.existing = plugin.settings.templatePath;
    this.files = this.app.vault.getMarkdownFiles().sort((a, b) => a.path.localeCompare(b.path));
    this.selected = new Set(plugin.settings.selected.filter(p => this.files.some(f => f.path === p)));
    this.query = '';
    this.parent = plugin.settings.parentPath;
    this.name = this.t('templatePrefix') + new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
  }
  render() {
    const el = this.begin('setTitle');
    description(el, this.t('saveIntro'));
    new Setting(el).setName(this.t('existingFolder')).addText(t => t.setValue(this.existing).onChange(v => { this.existing = v.trim(); }))
      .addButton(b => b.setButtonText(this.t('useTemplate')).onClick(() => this.run(b, async () => {
        const result = await ops.listTemplate(this.existing);
        this.plugin.settings.templatePath = result.root;
        await this.plugin.save(); new Notice(this.t('templateSet')); this.close(); this.plugin.openHome();
      })));
    new Setting(el).setName(this.t('saveHeading')).setHeading();
    new Setting(el).setName(this.t('selectNotes')).addText(t => t.setValue(this.query).setPlaceholder(this.t('search')).onChange(v => { this.query = v.toLowerCase(); renderList(); }));
    const count = el.createEl('p', { cls: 'vault-template-muted' });
    const list = el.createDiv({ cls: 'vault-template-list' });
    const renderList = () => {
      list.empty(); count.setText(this.t('selected', { count: this.selected.size }));
      for (const file of this.files.filter(f => f.path.toLowerCase().includes(this.query))) {
        new Setting(list).setName(file.path).addToggle(t => t.setValue(this.selected.has(file.path)).onChange(on => {
          if (on) this.selected.add(file.path); else this.selected.delete(file.path);
          count.setText(this.t('selected', { count: this.selected.size }));
        }));
      }
    };
    renderList();
    new Setting(el).setName(this.t('templateName')).addText(t => t.setValue(this.name).onChange(v => { this.name = v; }));
    new Setting(el).setName(this.t('templateLocation')).setDesc(this.t('outsideHint'))
      .addText(t => t.setValue(this.parent).onChange(v => { this.parent = v.trim(); }));
    description(el, this.t('attachmentHint'));
    new Setting(el).addButton(b => b.setButtonText(this.t('saveTemplate')).setCta().onClick(() => this.run(b, async () => {
      const attachments = new Set();
      for (const file of this.selected) {
        for (const linked of Object.keys(this.app.metadataCache.resolvedLinks[file] || {})) {
          const item = this.app.vault.getAbstractFileByPath(linked);
          if (item && item.extension && !['md', 'canvas', 'base'].includes(item.extension)) attachments.add(linked);
        }
      }
      const result = await ops.snapshot({ vaultRoot: this.plugin.root, selected: [...this.selected], attachments: [...attachments], parent: this.parent, name: this.name.trim(), configDir: this.app.vault.configDir });
      this.plugin.settings.templatePath = result.target;
      this.plugin.settings.selected = [...this.selected];
      await this.plugin.save(); new Notice(this.t('saved')); this.close(); this.plugin.openHome();
    })));
  }
}

class TemplateSettingTab extends PluginSettingTab {
  constructor(app, plugin) { super(app, plugin); this.plugin = plugin; }
  display() {
    const el = this.containerEl;
    el.empty();
    languageSetting(el, this.plugin);
    description(el, this.plugin.t('templatePath', { path: this.plugin.settings.templatePath }));
    new Setting(el).setName(this.plugin.t('manage')).setDesc(this.plugin.t('manageHint'))
      .addButton(b => b.setButtonText(this.plugin.t('open')).setCta().onClick(() => this.plugin.openHome()));
    description(el, this.plugin.t('localHint'));
  }
}

module.exports = VaultTemplatePlugin;
